# Generated by Django 3.1.4 on 2020-12-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar_graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='expert_tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.IntegerField(max_length=12)),
                ('FIO', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='General_proek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIN', models.IntegerField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Generalnyi_podryadchik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIN', models.IntegerField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gotovnost_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common', models.BooleanField(default=False)),
                ('fundament', models.BooleanField(default=False)),
                ('carcas', models.BooleanField(default=False)),
                ('crovlya', models.BooleanField(default=False)),
                ('ingener_net', models.BooleanField(default=False)),
                ('otdel', models.BooleanField(default=False)),
                ('salbotochnye', models.BooleanField(default=False)),
                ('blagoustr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ITR_sostav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.IntegerField(max_length=12)),
                ('familya', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otchestvo', models.CharField(max_length=50)),
                ('specializacia', models.CharField(max_length=50)),
                ('nomer_attestata', models.CharField(max_length=50)),
                ('data_attestata', models.DateField()),
                ('attestacionnyi_center', models.CharField(max_length=50)),
                ('BIN', models.IntegerField()),
                ('name_org', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='izmenenie_v_proekte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sut_izmenenie', models.TextField()),
                ('osnovanie', models.TextField()),
                ('data_soglasovaine', models.DateField()),
                ('result_sogl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Org_avtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIN', models.IntegerField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='primichanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primichanie', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='sdacha_Otcheta_tech_Nadzora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otchetnyi_organ', models.CharField(choices=[('Nur-Sultan', 'Nur-Sultan'), ('Almaty', 'Almaty'), ('Akmolinskaya oblast', 'Akmolinskaya oblast'), ('Aktubinskaya oblast', 'Aktubinskaya oblast'), ('Almatinskaya oblast', 'Almatinskaya oblast'), ('Atyrauskaya oblast', 'Atyrauskaya oblast'), ('ZKO', 'ZKO'), ('Zhambylskaya oblast', 'Zhambylskaya oblast'), ('Karagandinskaya oblast', 'Karagandinskaya oblast'), ('Kostanaiskaya oblast', 'Kostanaiskaya oblast')], max_length=100)),
                ('raion', models.CharField(choices=[('Almatinski raion', 'Almatinski raion'), ('Baikonurski raion', 'Baikonurski raion'), ('Esilski raion', 'Esilski raion'), ('Saryarkinski raion', 'Saryarkinski raion'), ('Alatauski raion', 'Alatauski raion'), ('Almatinski raion', 'Almatinski raion'), ('Auzovski raion', 'Auzovski raion'), ('Bostandykski raion', 'Bostandykski raion'), ('Zhetysuiski raion', 'Zhetysuiski raion'), ('Medeuski raion', 'Medeuski raion'), ('Naurizbayski raion', 'Naurizbayski raion')], max_length=100)),
                ('Nazvanie_obj', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='soderzhanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.BooleanField(choices=[(True, 'passport sootvetstvuet'), (False, 'passport ne ootvetstvuet')])),
                ('ograzhdenie', models.BooleanField(choices=[(True, 'ograzhdenie sootvetstvuet'), (False, 'ograzhdenie ne ootvetstvuet')])),
                ('moika', models.BooleanField(choices=[(True, 'imeetsya punkt moika koles'), (False, 'ootvetstvuet punkt moika koles')])),
                ('bunker', models.BooleanField(choices=[(True, 'imeetsya ustroistvo ili bunker'), (False, 'ootvetstvuet ustroistvo ili bunker')])),
                ('tverdie', models.BooleanField(choices=[(True, 'imeetsya tverdie pokritie'), (False, 'ootvetstvuet tverdie pokritie')])),
                ('ohrana', models.BooleanField(choices=[(True, 'sobludaetsa trebovaine po ohrane truda '), (False, 'ne sobludaetsa trebovaine po ohrane truda')])),
            ],
        ),
        migrations.CreateModel(
            name='sostoyanie_ispolnitelno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(choices=[(True, 'Vedetsya v polnom obyeme'), (False, 'Ne vedetsya v polnom obyeme')])),
            ],
        ),
        migrations.CreateModel(
            name='Subpodryadnye_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIN', models.IntegerField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Talon_Cmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomer_uvedomlenye', models.IntegerField()),
                ('data_uvedomlenye', models.DateField()),
                ('uroven_otvetstvennosti', models.CharField(choices=[('I(povyshennogo) urovnya', '1(povyshennogo) urovnya'), ('II (norm) urovnya otvetstvennosty', 'II (norm) urovnya otvetstvennosty'), ('III (norm) urovnya otvetstvennosty, ne otnosyashyeasya k tech slozhnym', 'III (norm) urovnya otvetstvennosty, ne otnosyashyeasya k tech slozhnym'), ('IV (norm) urovnya otvetstvennosty', 'IV (norm) urovnya otvetstvennosty')], max_length=120)),
                ('istochnik_finansirovanya', models.CharField(choices=[('Respublicansky byudzhet', 'Respublicansky byudzhet'), ('Mestny byudzhet', 'Mestny byudzhet'), ('Kvazhigos sector', 'Kvazhigos sector'), ('Chastnye inves', 'Chastnye inves'), ('Inostrannye inves', 'Inostrannye inves')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vydannie_zamechanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamechanie', models.TextField()),
                ('date_vydachi', models.DateField()),
                ('date_ustranenie', models.DateField()),
                ('neobhodimie_mery', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Zakazchik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIN', models.IntegerField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
