# Generated by Django 3.1.4 on 2020-12-18 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_tech',
            name='IIN',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
        ),
        migrations.AlterField(
            model_name='general_proek',
            name='BIN',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
        ),
        migrations.AlterField(
            model_name='generalnyi_podryadchik',
            name='BIN',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
        ),
        migrations.AlterField(
            model_name='itr_sostav',
            name='IIN',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
        ),
        migrations.AlterField(
            model_name='org_avtor',
            name='BIN',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
        ),
        migrations.AlterField(
            model_name='subpodryadnye_org',
            name='BIN',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
        ),
        migrations.AlterField(
            model_name='zakazchik',
            name='BIN',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
        ),
    ]
