# Generated by Django 3.1.4 on 2020-12-20 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201218_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdacha_otcheta_tech_nadzora',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sdacha', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sdacha_otcheta_tech_nadzora',
            name='Address',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='sdacha_otcheta_tech_nadzora',
            name='Nazvanie_obj',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='sdacha_otcheta_tech_nadzora',
            name='otchetnyi_organ',
            field=models.CharField(choices=[('Nur-Sultan', 'Nur-Sultan'), ('Almaty', 'Almaty'), ('Akmolinskaya oblast', 'Akmolinskaya oblast'), ('Aktubinskaya oblast', 'Aktubinskaya oblast'), ('Almatinskaya oblast', 'Almatinskaya oblast'), ('Atyrauskaya oblast', 'Atyrauskaya oblast'), ('ZKO', 'ZKO'), ('Zhambylskaya oblast', 'Zhambylskaya oblast'), ('Karagandinskaya oblast', 'Karagandinskaya oblast'), ('Kostanaiskaya oblast', 'Kostanaiskaya oblast')], default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='sdacha_otcheta_tech_nadzora',
            name='raion',
            field=models.CharField(choices=[('Almatinski raion', 'Almatinski raion'), ('Baikonurski raion', 'Baikonurski raion'), ('Esilski raion', 'Esilski raion'), ('Saryarkinski raion', 'Saryarkinski raion'), ('Alatauski raion', 'Alatauski raion'), ('Almatinski raion', 'Almatinski raion'), ('Auzovski raion', 'Auzovski raion'), ('Bostandykski raion', 'Bostandykski raion'), ('Zhetysuiski raion', 'Zhetysuiski raion'), ('Medeuski raion', 'Medeuski raion'), ('Naurizbayski raion', 'Naurizbayski raion')], default='SOME STRING', max_length=100),
        ),
    ]
