# Generated by Django 3.1.4 on 2020-12-20 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_sdacha_otcheta_tech_nadzora_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdacha_otcheta_tech_nadzora',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdacha', to=settings.AUTH_USER_MODEL),
        ),
    ]
