# Generated by Django 3.1.4 on 2020-12-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201220_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdacha_otcheta_tech_nadzora',
            name='owner',
        ),
    ]
