# Generated by Django 3.1.4 on 2020-12-21 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_sdacha_otcheta_tech_nadzora_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon_cmp',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='talon', to=settings.AUTH_USER_MODEL),
        ),
    ]
