# Generated by Django 3.1.4 on 2020-12-21 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_talon_cmp_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_graphic',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_graphic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='general_proek',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='general_proek', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalnyi_podryadchik',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='generalnyi_podryadchik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gotovnost_obj',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gotovnost_obj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='org_avtor',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='org_avtor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sostoyanie_ispolnitelno',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sostoyanie_ispolnitelno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subpodryadnye_org',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subpodryadnye_org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zakazchik',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='zakazchik', to=settings.AUTH_USER_MODEL),
        ),
    ]
