# Generated by Django 3.1.4 on 2020-12-21 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20201221_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_tech',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expert_tech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itr_sostav',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='itr_sostav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='izmenenie_v_proekte',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='izmenenie_v_proekte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='primichanie',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primichanie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soderzhanie',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='soderzhanie', to=settings.AUTH_USER_MODEL),
        ),
    ]
