# Generated by Django 3.1.4 on 2020-12-21 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20201221_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='vydannie_zamechanie',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vydannie_zamechanie', to=settings.AUTH_USER_MODEL),
        ),
    ]
